---
name: Testing for dovecot-fts-flatcurve

on:
  push:
    paths:
      - 'src/**'
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu_test:
    name: Testing on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: .github
      - name: Copy test files to base directory
        run: |
          cp -av ./.github/actions/flatcurve-test-ubuntu/* ./
          cp -av ./.github/common/* ./
      - uses: ./
  alpine_test:
    name: Testing on Alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: .github
      - name: Copy test files to base directory
        run: |
          cp -av ./.github/actions/flatcurve-test-alpine/* ./
          cp -av ./.github/common/* ./
      - uses: ./
