---
name: Testing for dovecot-fts-flatcurve

on:
  push:
    paths:
      - 'src/**'
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu_test:
    name: Testing on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy common files to working directory
        run: cp -av ./.github/common/* ./.github/actions/flatcurve-test-ubuntu/
      - uses: ./.github/actions/flatcurve-test-ubuntu/action.yml
  alpine_test:
    name: Testing on Alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy common files to working directory
        run: cp -av ./.github/common/* ./.github/actions/flatcurve-test-alpine/
      - uses: ./.github/actions/flatcurve-test-alpine/action.yml
