---
name: Testing for dovecot-fts-flatcurve

on:
  push:
    paths:
      - 'src/**'
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/flatcurve-test/action-ubuntu.yml
